database = "memento"

[memento_agent]
provider = "anthropic"
model = "sonnet"
temperature = 0.5

[synopsis_agent]
provider = "anthropic"
model = "haiku"
temperature = 0.0
max_tokens = 1000

[resolution_agent]
provider = "anthropic"
model = "haiku"
temperature = 0.0

[conversation]
max_exchanges = 5
max_tokens = 3000

[search]
max_tokens = 10000
keywords = 5

    [search.decay]
    user = 0.6
    asst = 0.4
