database = "memento"

[memento_agent]
role = "memento"
provider = "anthropic"
model = "haiku"
temperature = 0
max_response_tokens = 2000

[resolution_agent]
role = "resolution"
provider = "anthropic"
model = "haiku"
temperature = 0
max_response_tokens = 200

[synopsis_agent]
role = "synopsis"
provider = "anthropic"
model = "haiku"
temperature = 0
max_response_tokens = 100

[search_context]
keywords = 5
tokens = 8000

[search_context.weight]
user = 0.5
asst = 0.5

[synopses]
max_tokens = 3000

[conversation_snapshot]
max_exchanges = 5
max_tokens = 3000
