database = "db_sonnet35_jun_20"

[memento_agent]
provider = "anthropic"
model = "sonnet35"
temperature = 0.25
role = "memento"

[synopsis_agent]
provider = "anthropic"
model = "sonnet35"
temperature = 0
max_tokens = 60
role = "synopsis"

[resolution_agent]
provider = "anthropic"
model = "sonnet35"
temperature = 0
role = "resolution"

[conversation]
max_exchanges = 5
max_tokens = 4000

[search]
max_tokens = 15000
keywords = 5

    [search.decay]
    user = 0.6
    asst = 0.4
